### ISSUE TITLE
sorl-thumbnail 3.2.5 version dependance

### ISSUE THREAD

**Issue by sirex** [caktus/django-file-picker#15]
Why you depend on such old sorl-thumbnail version? In my project I already use newest sorl-thumbnail version, bet when I tried to downgrade it to 3.2.5, in my code I got this error: 

```
from sorl.thumbnail import ImageField
ImportError: cannot import name ImageField
```

**Comment by vkurup** [comment]
sorl-thumbnail has been upgraded.
